Models/Activite.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace appli_gest_assoc.Models
{
    public partial class Activite
    {
        public Activite()
        {
            Bureaus = new HashSet<Bureau>();
        }

        public int IdActivite { get; set; }
        public string Libelle { get; set; }

        public virtual ICollection<Bureau> Bureaus { get; set; }
    }
}

Controllers/ActivitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using appli_gest_assoc.Models;

namespace appli_gest_assoc.Controllers
{
    public class ActivitesController : Controller
    {
        private readonly gest_assoc_dbContext _context;

        public ActivitesController(gest_assoc_dbContext context)
        {
            _context = context;
        }

        // GET: Activites
        public async Task<IActionResult> Index(string movieGenre, string searchString)
        {
            IQueryable<string> genreQuery = from a in _context.Activites
                                            orderby a.Libelle
                                            select a.Libelle;

            var movies = from a in _context.Activites
                         select a;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Libelle.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Libelle == movieGenre);
            }

            var nomActiviteVM = new ActiviteSearching
            {
                NomActivite = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Activites = await movies.ToListAsync()
            };

            return View(nomActiviteVM);
        }

        // GET: Activites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activite = await _context.Activites
                .FirstOrDefaultAsync(m => m.IdActivite == id);
            if (activite == null)
            {
                return NotFound();
            }

            return View(activite);
        }

        // GET: Activites/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Activites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdActivite,Libelle")] Activite activite)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activite);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(activite);
        }

        // GET: Activites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activite = await _context.Activites.FindAsync(id);
            if (activite == null)
            {
                return NotFound();
            }
            return View(activite);
        }

        // POST: Activites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdActivite,Libelle")] Activite activite)
        {
            if (id != activite.IdActivite)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActiviteExists(activite.IdActivite))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(activite);
        }

        // GET: Activites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activite = await _context.Activites
                .FirstOrDefaultAsync(m => m.IdActivite == id);
            if (activite == null)
            {
                return NotFound();
            }

            return View(activite);
        }

        // POST: Activites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activite = await _context.Activites.FindAsync(id);
            _context.Activites.Remove(activite);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActiviteExists(int id)
        {
            return _context.Activites.Any(e => e.IdActivite == id);
        }
    }
}

Views/Activites/Create.cshtml
@model appli_gest_assoc.Models.Activite

@{
    ViewData["Title"] = "Create";
}

@{
    ViewData["Title"] = "Ajouter une activité";
}

<div class="container">

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb pull-right">
                <li><a asp-controller="Home" asp-action="Index">Sofa</a></li>
                <li><a asp-controller="Acticites" asp-action="Index">Activité</a></li>
                <li class="active">Ajouter une activité</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Ajouter une activité</h3></div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="post" asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="col-md-2 control-label" asp-for="Libelle">Activité</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" id="nom" placeholder="Saisir le libellé" asp-for="Libelle" required="true">
                                <span asp-validation-for="Libelle" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col text-center">
                                    <button type="submit" class="btn btn-primary btn-custom waves-effect waves-light m-b-5 btn-lg">Ajouter</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div> <!-- panel-body -->
            </div> <!-- panel -->
        </div> <!-- col -->
    </div>
</div> <!-- container -->

Views/Activites/Delete.cshtml
@model appli_gest_assoc.Models.Activite

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading text-center"><h3 class="panel-title">Supprimer une activité</h3></div>
            <div class="panel-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        Activité
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Libelle)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for="IdActivite" />
    <input type="submit" value="Supprimer" class="btn btn-danger" />
</form>

Views/Activites/Details.cshtml
@model appli_gest_assoc.Models.Activite

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Activité
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdActivite">Modifier</a>
</div>

Views/Activites/Edit.cshtml
@model appli_gest_assoc.Models.Activite

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Modifier une activité</h3></div>
            <div class="panel-body">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdActivite" />
                    <div class="form-group">
                        <label asp-for="Libelle" class="control-label">Activité</label>
                        <input asp-for="Libelle" class="form-control" required=""/>
                        <span asp-validation-for="Libelle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Activites/Index.cshtml
@model appli_gest_assoc.Models.ActiviteSearching

@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb pull-right">
                <li><a asp-controller="Home" asp-action="Index">Sofa</a></li>
                <li><a asp-controller="Activites" asp-action="Index">Acitivité</a></li>
                <li class="active">Liste des activités</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-heading">
                        <h3 class="panel-title">Liste des activités</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <form asp-controller="Activites" asp-action="Index" method="get">
                                    <p>
                                        <input type="text" asp-for="SearchString" placeholder="Nom de l'activité'"/>
                                        <button class="btn btn-primary" type="submit">Filtrer</button>
                                    </p>
                                </form><br />
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>
                                                Activité
                                            </th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>


                                    <tbody>

                                        @foreach (var item in Model.Activites)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Libelle)
                                                </td>
                                                <td>
                                                    <a asp-action="Edit" asp-route-id="@item.IdActivite"><i class="fa fa-edit"></i></a> |
                                                    <a asp-action="Delete" asp-route-id="@item.IdActivite"><i class="fa fa-trash"></i></a>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- End Row -->


    </div>
</div>