Controllers/TypeDepensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using appli_gest_assoc.Models;

namespace appli_gest_assoc.Controllers
{
    public class TypeDepensesController : Controller
    {
        private readonly gest_assoc_dbContext _context;

        public TypeDepensesController(gest_assoc_dbContext context)
        {
            _context = context;
        }

        // GET: TypeDepenses
        public async Task<IActionResult> Index(string movieGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from t in _context.TypeDepenses
                                            orderby t.Libelle
                                            select t.Libelle;

            var movies = from t in _context.TypeDepenses
                         select t;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Libelle.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Libelle == movieGenre);
            }

            var typeDepenseVM = new TypeDepenseSearching
            {
                NomTypeDepense = new SelectList(await genreQuery.Distinct().ToListAsync()),
                TypeDepenses = await movies.ToListAsync()
            };

            return View(typeDepenseVM);
        }

        // GET: TypeDepenses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeDepense = await _context.TypeDepenses
                .FirstOrDefaultAsync(m => m.IdTypeDepense == id);
            if (typeDepense == null)
            {
                return NotFound();
            }

            return View(typeDepense);
        }

        // GET: TypeDepenses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TypeDepenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTypeDepense,Libelle")] TypeDepense typeDepense)
        {
            if (ModelState.IsValid)
            {
                _context.Add(typeDepense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(typeDepense);
        }

        // GET: TypeDepenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeDepense = await _context.TypeDepenses.FindAsync(id);
            if (typeDepense == null)
            {
                return NotFound();
            }
            return View(typeDepense);
        }

        // POST: TypeDepenses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTypeDepense,Libelle")] TypeDepense typeDepense)
        {
            if (id != typeDepense.IdTypeDepense)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(typeDepense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeDepenseExists(typeDepense.IdTypeDepense))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(typeDepense);
        }

        // GET: TypeDepenses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeDepense = await _context.TypeDepenses
                .FirstOrDefaultAsync(m => m.IdTypeDepense == id);
            if (typeDepense == null)
            {
                return NotFound();
            }

            return View(typeDepense);
        }

        // POST: TypeDepenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var typeDepense = await _context.TypeDepenses.FindAsync(id);
            _context.TypeDepenses.Remove(typeDepense);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TypeDepenseExists(int id)
        {
            return _context.TypeDepenses.Any(e => e.IdTypeDepense == id);
        }
    }
}

Views/TypeDepenses/Create.cshtml
@model appli_gest_assoc.Models.TypeDepense

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Ajouter un type de dépense</h3></div>
            <div class="panel-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Libelle" class="control-label"></label>
                        <input asp-for="Libelle" class="form-control" required=""/>
                        <span asp-validation-for="Libelle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ajouter" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

Views/TypeDepenses/Delete.cshtml
@model appli_gest_assoc.Models.TypeDepense

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading text-center"><h3 class="panel-title">Suppression</h3></div>
            <div class="panel-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        Libellé :
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Libelle)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="IdTypeDepense" />
                    <input type="submit" value="Supprimer" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

Views/TypeDepenses/Details.cshtml
@model appli_gest_assoc.Models.TypeDepense

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TypeDepense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdTypeDepense">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/TypeDepenses/Edit.cshtml
@model appli_gest_assoc.Models.TypeDepense

@{
    ViewData["Title"] = "Edit";
}

<hr />
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Modifier le type de dépense</h3></div>
            <div class="panel-body">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdTypeDepense" />
                    <div class="form-group">
                        <label asp-for="Libelle" class="control-label"></label>
                        <input asp-for="Libelle" class="form-control" required=""/>
                        <span asp-validation-for="Libelle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/TypeDepenses/Index.cshtml
@model appli_gest_assoc.Models.TypeDepenseSearching

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-heading">
                    <h3 class="panel-title">Liste des types de dépense</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <form asp-controller="TypeDepenses" asp-action="Index" method="get">
                                    <p>
                                        <input type="text" asp-for="SearchString" placeholder="Libellé"/>
                                        <button class="btn btn-primary" type="submit">Filtrer</button>
                                    </p>
                                </form><br />
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            Libellé
                                        </th>
                                        <th>
                                            Actions
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.TypeDepenses)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Libelle)
                                            </td>
                                            <td>
                                                <a asp-action="Edit" asp-route-id="@item.IdTypeDepense"><i class="fa fa-edit"></i></a> |
                                                @*<a asp-action="Details" asp-route-id="@item.IdTypeDepense">Details</a> |*@
                                                <a asp-action="Delete" asp-route-id="@item.IdTypeDepense"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <p><a asp-controller="TypeDepenses" asp-action="Create">Ajouter un type de dépense</a></p>
            </div>
        </div>
    </div>
</div>