Models/TypeRecette.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace appli_gest_assoc.Models
{
    public partial class TypeRecette
    {
        public TypeRecette()
        {
            Recettes = new HashSet<Recette>();
        }

        public int IdTypeRecette { get; set; }
        public string Libelle { get; set; }

        public virtual ICollection<Recette> Recettes { get; set; }
    }
}

Controllers/TypeRecettesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using appli_gest_assoc.Models;

namespace appli_gest_assoc.Controllers
{
    public class TypeRecettesController : Controller
    {
        private readonly gest_assoc_dbContext _context;

        public TypeRecettesController(gest_assoc_dbContext context)
        {
            _context = context;
        }

        // GET: TypeRecettes
        public async Task<IActionResult> Index(string movieGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from t in _context.TypeRecettes
                                            orderby t.Libelle
                                            select t.Libelle;

            var movies = from t in _context.TypeRecettes
                         select t;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Libelle.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Libelle == movieGenre);
            }

            var typeRecetteVM = new TypeRecetteSearching
            {
                NomTypeRecette = new SelectList(await genreQuery.Distinct().ToListAsync()),
                TypeRecettes = await movies.ToListAsync()
            };

            return View(typeRecetteVM);
        }



        // GET: TypeRecettes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeRecette = await _context.TypeRecettes
                .FirstOrDefaultAsync(m => m.IdTypeRecette == id);
            if (typeRecette == null)
            {
                return NotFound();
            }

            return View(typeRecette);
        }

        // GET: TypeRecettes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TypeRecettes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTypeRecette,Libelle")] TypeRecette typeRecette)
        {
            if (ModelState.IsValid)
            {
                _context.Add(typeRecette);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(typeRecette);
        }

        // GET: TypeRecettes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeRecette = await _context.TypeRecettes.FindAsync(id);
            if (typeRecette == null)
            {
                return NotFound();
            }
            return View(typeRecette);
        }

        // POST: TypeRecettes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTypeRecette,Libelle")] TypeRecette typeRecette)
        {
            if (id != typeRecette.IdTypeRecette)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(typeRecette);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeRecetteExists(typeRecette.IdTypeRecette))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(typeRecette);
        }

        // GET: TypeRecettes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeRecette = await _context.TypeRecettes
                .FirstOrDefaultAsync(m => m.IdTypeRecette == id);
            if (typeRecette == null)
            {
                return NotFound();
            }

            return View(typeRecette);
        }

        // POST: TypeRecettes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var typeRecette = await _context.TypeRecettes.FindAsync(id);
            _context.TypeRecettes.Remove(typeRecette);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TypeRecetteExists(int id)
        {
            return _context.TypeRecettes.Any(e => e.IdTypeRecette == id);
        }
    }
}

Views/TypeRecettes/Create.cshtml
@model appli_gest_assoc.Models.TypeRecette

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Ajouter un type de recette</h3></div>
            <div class="panel-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Libelle" class="control-label"></label>
                        <input asp-for="Libelle" class="form-control" required=""/>
                        <span asp-validation-for="Libelle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ajouter" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

Views/TypeRecettes/Delete.cshtml
@model appli_gest_assoc.Models.TypeRecette

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading text-center"><h3 class="panel-title">Suppression</h3></div>
            <div class="panel-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        Libellé:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Libelle)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input type="hidden" asp-for="IdTypeRecette" />
                    <input type="submit" value="Supprimer" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

Views/TypeRecettes/Details.cshtml
@model appli_gest_assoc.Models.TypeRecette

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TypeRecette</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdTypeRecette">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/TypeRecettes/Edit.cshtml
@model appli_gest_assoc.Models.TypeRecette

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Modifier une type de recette</h3></div>
            <div class="panel-body">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdTypeRecette" />
                    <div class="form-group">
                        <label asp-for="Libelle" class="control-label"></label>
                        <input asp-for="Libelle" class="form-control" required=""/>
                        <span asp-validation-for="Libelle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/TypeRecettes/Index.cshtml
@model appli_gest_assoc.Models.TypeRecetteSearching

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-heading">
                    <h3 class="panel-title">Liste des types de recette</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <form asp-controller="TypeRecettes" asp-action="Index" method="get">
                                    <p>
                                        <input type="text" asp-for="SearchString" placeholder="Libellé"/>
                                        <button class="btn btn-primary" type="submit">Filtrer</button>
                                    </p>
                                </form><br />
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            Libellé
                                        </th>
                                        <th>
                                            Actions
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.TypeRecettes)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Libelle)
                                            </td>
                                            <td>
                                                <a asp-action="Edit" asp-route-id="@item.IdTypeRecette"><i class="fa fa-edit"></i></a> |
                                                @*      <a asp-action="Details" asp-route-id="@item.IdTypeRecette">Details</a> |*@
                                                <a asp-action="Delete" asp-route-id="@item.IdTypeRecette"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <p><a asp-controller="TypeRecettes" asp-action="Create">Ajouter un type de recette</a></p>
            </div>
        </div>
    </div>
</div>