Controllers/MembreBureauxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using appli_gest_assoc.Models;

namespace appli_gest_assoc.Controllers
{
    public class MembreBureauxController : Controller
    {
        private readonly gest_assoc_dbContext _context;

        public MembreBureauxController(gest_assoc_dbContext context)
        {
            _context = context;
        }

        // GET: MembreBureaux
        public async Task<IActionResult> Index()
        {
            var gest_assoc_dbContext = _context.MembreBureaus.Include(m => m.Bureau).Include(m => m.Membre);
            return View(await gest_assoc_dbContext.ToListAsync());
        }

        // GET: MembreBureaux/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membreBureau = await _context.MembreBureaus
                .Include(m => m.Bureau)
                .Include(m => m.Membre)
                .FirstOrDefaultAsync(m => m.IdMembreBureau == id);
            if (membreBureau == null)
            {
                return NotFound();
            }

            return View(membreBureau);
        }

        // GET: MembreBureaux/Create
        public IActionResult Create()
        {
            ViewData["BureauId"] = new SelectList(_context.Bureaus, "IdBureau", "NomBureau");
            ViewData["MembreId"] = new SelectList(_context.Membres, "IdMembre", "IdMembre");
            return View();
        }

        // POST: MembreBureaux/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMembreBureau,MembreId,DateCreation,Poste,BureauId")] MembreBureau membreBureau)
        {
            if (ModelState.IsValid)
            {
                _context.Add(membreBureau);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BureauId"] = new SelectList(_context.Bureaus, "IdBureau", "NomBureau", membreBureau.BureauId);
            ViewData["MembreId"] = new SelectList(_context.Membres, "IdMembre", "IdMembre", membreBureau.MembreId);
            return View(membreBureau);
        }

        // GET: MembreBureaux/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membreBureau = await _context.MembreBureaus.FindAsync(id);
            if (membreBureau == null)
            {
                return NotFound();
            }
            ViewData["BureauId"] = new SelectList(_context.Bureaus, "IdBureau", "NomBureau", membreBureau.BureauId);
            ViewData["MembreId"] = new SelectList(_context.Membres, "IdMembre", "IdMembre", membreBureau.MembreId);
            return View(membreBureau);
        }

        // POST: MembreBureaux/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMembreBureau,MembreId,DateCreation,Poste,BureauId")] MembreBureau membreBureau)
        {
            if (id != membreBureau.IdMembreBureau)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membreBureau);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembreBureauExists(membreBureau.IdMembreBureau))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BureauId"] = new SelectList(_context.Bureaus, "IdBureau", "NomBureau", membreBureau.BureauId);
            ViewData["MembreId"] = new SelectList(_context.Membres, "IdMembre", "IdMembre", membreBureau.MembreId);
            return View(membreBureau);
        }

        // GET: MembreBureaux/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membreBureau = await _context.MembreBureaus
                .Include(m => m.Bureau)
                .Include(m => m.Membre)
                .FirstOrDefaultAsync(m => m.IdMembreBureau == id);
            if (membreBureau == null)
            {
                return NotFound();
            }

            return View(membreBureau);
        }

        // POST: MembreBureaux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var membreBureau = await _context.MembreBureaus.FindAsync(id);
            _context.MembreBureaus.Remove(membreBureau);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembreBureauExists(int id)
        {
            return _context.MembreBureaus.Any(e => e.IdMembreBureau == id);
        }
    }
}

Views/MembreBureaux/Create.cshtml
@model appli_gest_assoc.Models.MembreBureau

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Ajouter un membre de bureau</h3></div>
            <div class="panel-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="MembreId" class="control-label">Matricule</label>
                        <select asp-for="MembreId" class="form-control" asp-items="ViewBag.MembreId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateCreation" class="control-label">Date de création</label>
                        <input asp-for="DateCreation" class="form-control" />
                        <span asp-validation-for="DateCreation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Poste" class="control-label">Poste</label>
                        <input asp-for="Poste" class="form-control" required=""/>
                        <span asp-validation-for="Poste" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BureauId" class="control-label">Bureau</label>
                        <select asp-for="BureauId" class="form-control" asp-items="ViewBag.BureauId"></select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ajouter" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/MembreBureaux/Delete.cshtml
@model appli_gest_assoc.Models.MembreBureau

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading text-center"><h3 class="panel-title">Supprimer un membre de bureau</h3></div>
            <div class="panel-body">
    <dl class="row">
        <dt class = "col-sm-2">
            Date de création
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreation)
        </dd>
        <dt class = "col-sm-2">
            Poste
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            Bureau
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bureau.NomBureau)
        </dd class>
        <dt class = "col-sm-2">
            Membre
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Membre.NomMembre)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdMembreBureau" />
        <input type="submit" value="Supprimer" class="btn btn-danger" />
    </form>
</div>
</div>
</div>
</div>

Views/MembreBureaux/Details.cshtml
@model appli_gest_assoc.Models.MembreBureau

@{
    ViewData["Title"] = "Details";
}

<div class="content">
    <div class="wraper container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="bg-light text-center">
                    <div class="bg-picture text-center" style="background-image:url('images/big/bg.jpg')"></div>
                    <div class="profile-info-name">
                        <!-- <img src="images/avatar-1.jpg" class="thumb-lg img-circle img-thumbnail" alt="profile-image"> -->
                        <h3 class="text-dark mb-auto">@Model.Bureau.NomBureau</h3>
                    </div>
                </div>
                <!--/ meta -->
            </div>
        </div>
        <div class="row user-tabs">
            <div class="col-lg-6 col-md-9 col-sm-9">
                <ul class="nav nav-tabs tabs">
                    <li class="active tab">
                        <a href="#home-2" data-toggle="tab" aria-expanded="false" class="active">
                            <span class="visible-xs"><i class="fa fa-home"></i></span>
                            <span class="hidden-xs">Infos</span>
                        </a>
                    </li>
                    @*               <li class="tab">
                    <a href="#settings-2" data-toggle="tab" aria-expanded="false">
                    <span class="visible-xs"><i class="fa fa-cog"></i></span>
                    <span class="hidden-xs">Paramètres</span>
                    </a>
                    </li>*@
                    <div class="indicator"></div>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">

                <div class="tab-content profile-tab-content">
                    <div class="tab-pane active" id="home-2">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- Personal-Information -->
                                <div class="panel panel-default panel-fill">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Informations sur l'organisation</h3>
                                    </div>
                                    <div class="panel-body">
                                        <div class="about-info-p">
                                            <strong>Bureau</strong>
                                            <br />
                                            <p class="text-muted">@Model.Bureau.NomBureau</p>
                                        </div>
                                        <div class="about-info-p">
                                            <strong>Matricule</strong>
                                            <br />
                                            <p class="text-muted">@Model.Membre.IdMembre</p>
                                        </div>
                                        <div class="about-info-p">
                                            <strong>Prénom</strong>
                                            <br />
                                            <p class="text-muted">@Model.Membre.PrenomMembre</p>
                                        </div>
                                        <div class="about-info-p">
                                            <strong>Nom</strong>
                                            <br />
                                            <p class="text-muted">@Model.Membre.NomMembre</p>
                                        </div>
                                        <div class="about-info-p">
                                            <strong>Poste</strong>
                                            <br />
                                            <p class="text-muted">@Model.Poste</p>
                                        </div>
                                        <div class="about-info-p m-b-0">
                                            <strong>Date de création</strong>
                                            <br />
                                            <p class="text-muted">@Model.DateCreation</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- Personal-Information -->

                            </div>

                        </div>
                    </div>




                </div>
            </div>
        </div>
    </div>
</div>

Views/MembreBureaux/Edit.cshtml
@model appli_gest_assoc.Models.MembreBureau

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Membre Bureau</h4>
<hr />
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Ajouter un membre de bureau</h3></div>
            <div class="panel-body">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IdMembreBureau" />
                    <div class="form-group">
                        <label asp-for="MembreId" class="control-label">Matricule</label>
                        <select asp-for="MembreId" class="form-control" asp-items="ViewBag.MembreId"></select>
                        <span asp-validation-for="MembreId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateCreation" class="control-label">Date de création</label>
                        <input asp-for="DateCreation" class="form-control" />
                        <span asp-validation-for="DateCreation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Poste" class="control-label">Poste</label>
                        <input asp-for="Poste" class="form-control" required=""/>
                        <span asp-validation-for="Poste" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BureauId" class="control-label">Bureau</label>
                        <select asp-for="BureauId" class="form-control" asp-items="ViewBag.BureauId"></select>
                        <span asp-validation-for="BureauId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

Views/MembreBureaux/Index.cshtml
@model IEnumerable<appli_gest_assoc.Models.MembreBureau>

@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <ol class="breadcrumb pull-right">
                <li><a asp-controller="Home" asp-action="Index">Sofa</a></li>
                <li><a asp-controller="MembreBureaux" asp-action="Index">Organisation du bureau</a></li>
                <li class="active">Liste des organisations</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-heading">
                        <h3 class="panel-title">Liste des organisations</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>
                                                Bureau
                                            </th>
                                            <th>
                                                Matricule
                                            </th>
                                            <th>
                                                Prénom
                                            </th>
                                            <th>
                                                Nom
                                            </th>
                                            <th>
                                                Poste
                                            </th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>


                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Bureau.NomBureau)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Membre.IdMembre)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Membre.PrenomMembre)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Membre.NomMembre)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Poste)
                                                </td>


                                                <td>
                                                    <a asp-action="Edit" asp-route-id="@item.IdMembreBureau"><i class="fa fa-edit"></i></a> |
                                                    <a asp-action="Details" asp-route-id="@item.IdMembreBureau"><i class="fa fa-list-alt"></i></a> |
                                                    <a asp-action="Delete" asp-route-id="@item.IdMembreBureau"><i class="fa fa-trash"></i></a>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- End Row -->


    </div>
</div>